# 1.) 
Write a NumPy program to convert a given array into a list and then convert it into a NumPy array again.

In [ ]:
import numpy as np
a1 = np.array(np.arange(10))
print(f"Type of a1 : {type(a1)}")
l1 = list(a1)
print(f"Type of l1 : {type(l1)}")
a2 = np.array(l1)
print(f"Type of a2 : {type(a2)}")

Type of a1 : <class 'numpy.ndarray'>
Type of l1 : <class 'list'>
Type of a2 : <class 'numpy.ndarray'>

# 2.) 
Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10.

In [ ]:
import numpy as np
a = np.arange(100, 200, 10).reshape(5, 2)
print(f"The 5X2 Array ::\n{a}")

The 5X2 Array ::
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]

# 3.) 
Add the two 2D NumPy arrays and modify the  resulting array by calculating the square root of each element.

In [ ]:
import numpy as np
x = np.random.rand(2, 2)
y = np.random.rand(2, 2)
print(f"Numpy Array 1 ::\n{x}\nNumpy Array 2 ::\n{y}")
print(f"Square root of each element after adding two 2D-Numpy array ::\n{np.sqrt(x + y)}")

Numpy Array 1 ::
[[0.45729302 0.37431231]
 [0.9474356  0.24607332]]
Numpy Array 2 ::
[[0.38587951 0.10096933]
 [0.77022659 0.92723291]]
Square root of each element after adding two 2D-Numpy array ::
[[0.91824427 0.68940673]
 [1.31059612 1.08319261]]

# 4.) 
Create an 8X3 integer array from a range between 10 to 34 such that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.

In [ ]:
import numpy as np
a = np.arange(10, 34, 1).reshape(8, 3)
print(f"The 8X3 Array ::\n{a}")
b = a.reshape(4, int(8*3/4))
print(f"The New Array ::\n{b}")

The 8X3 Array ::
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]
The New Array ::
[[10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]
 [28 29 30 31 32 33]]

# 5.) 
Consider the following array:\
sampleArray \= numpy\.array(\[\[34,43,73\],\[82,22,12\],\[53,94,66\]\])\
i. Sort above array by second row\
ii. Sort above array by second column\
iii. Print max from axis 0 and min from axis 1\
iv. Delete col 2 and insert new Column numpy.array(\[\[10,10,10]]) in its place

In [ ]:

import numpy as np

sampleArray = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
print(f"Sample Array ::\n{sampleArray}")

# i. Sort above array by second row

print(f"After sorting above array by second row ::\n{sampleArray[:, sampleArray[1].argsort()]}")

# ii. Sort above array by second column

print(f"After sorting above array by second column ::\n{sampleArray[sampleArray[:, 1].argsort(), :]}")

# iii. Print max from axis 0 and min from axis 1

print(f"Max from axis 0 : {np.max(sampleArray, axis=0)}\nMin from axis 1 : {np.min(sampleArray, axis=1)}")

# iv. Delete col 2 and insert new Column numpy.array([[10,10,10]]) in its place

sampleArray = np.delete(sampleArray, 1, axis=1)
print(f"After deleting col 2 from above array ::\n{sampleArray}")
sampleArray = np.insert(sampleArray, 1, np.array([[10, 10, 10]]), 1)
print(f"After inserting np.array([[10,10,10]]) in col 2 ::\n{sampleArray}")

Sample Array ::
[[34 43 73]
 [82 22 12]
 [53 94 66]]
After sorting above array by second row ::
[[73 43 34]
 [12 22 82]
 [66 94 53]]
After sorting above array by second column ::
[[82 22 12]
 [34 43 73]
 [53 94 66]]
Max from axis 0 : [82 94 73]
Min from axis 1 : [34 12 53]
After deleting col 2 from above array ::
[[34 73]
 [82 12]
 [53 66]]
After inserting np.array([[10,10,10]]) in col 2 ::
[[34 10 73]
 [82 10 12]
 [53 10 66]]

# 6.) 
Remove all the elemnets from an array that exist in another array?

In [ ]:
import numpy as np
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=6)
print(f"First Array : {x1}")
print(f"Second Array : {x2}")
x2 = np.unique(x2)
for i in x2:
    if i in x1:
        x1 = np.delete(x1, np.where(x1 == i))
print(f"First Array after removing elements from Second Array : {x1}")

First Array : [3 2 8 4 5 0]
Second Array : [4 5 4 1 2 6]
First Array after removing elements from Second Array : [3 8 0]

# 7.)
Swap two columns in a 2d NumPy array.

In [ ]:
import numpy as np
a = np.array(np.arange(1, 10)).reshape(3, 3)
print(f"2D-Array ::\n{a}")
temp = a[:,0].copy(); a[:,0]=a[:, 2];a[:,2]=temp
print(f"2D-Array after swapping column 0 and column 2 ::\n{a}")

2D-Array ::
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2D-Array after swapping column 0 and column 2 ::
[[3 2 1]
 [6 5 4]
 [9 8 7]]

# 8.)
Swap two rows in a 2d NumPy array.

In [22]:
import numpy as np
a = np.array(np.arange(1, 10)).reshape(3, 3)
print(f"2D-Array ::\n{a}")
temp = a[0, :].copy(); a[0, :]=a[2, :];a[2, :]=temp
print(f"2D-Array after swapping row 0 and row 2 ::\n{a}")

2D-Array ::
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2D-Array after swapping row 0 and row 2 ::
[[7 8 9]
 [4 5 6]
 [1 2 3]]

# 9.) 
Reverse the order of rows of a 2D array

In [21]:
import numpy as np
a = np.array(np.arange(1, 10)).reshape(3, 3)
print(f"2D-Array ::\n{a}")
a = a[::-1,:]
print(f"2D-Array after reversing the order of rows ::\n{a}")

2D-Array ::
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2D-Array after reversing the order of rows ::
[[7 8 9]
 [4 5 6]
 [1 2 3]]

# 10.)
Reverse the order of columns of a 2D array

In [20]:
import numpy as np
a = np.array(np.arange(1, 10)).reshape(3, 3)
print(f"2D-Array ::\n{a}")
a = a[:,::-1]
print(f"2D-Array after reversing the order of columns ::\n{a}")

2D-Array ::
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2D-Array after reversing the order of columns ::
[[3 2 1]
 [6 5 4]
 [9 8 7]]

# 11.)
Retrieve common items between two python NumPy arrays?

In [19]:
import numpy as np
arr1 = np.random.randint(0, 15, 10)
arr2 = np.random.randint(0, 15, 10)
print(f"Array 1 : {arr1}\nArray 2 : {arr2}")
print(f"Common items between two arrays : {np.intersect1d(arr1, arr2)}")

Array 1 : [ 1  8  4 12  5  3  8  3  1  8]
Array 2 : [14 13  5  5 13  5 11  1 13  0]
Common items between two arrays : [1 5]

# 12.)
Retrive indices where elements of two arrays match

In [16]:
import numpy as np

arr1 = np.random.randint(0, 15, 10)
arr2 = np.random.randint(0, 15, 10)
ind = np.where(arr1 == arr2)
print(f"Array 1 : {arr1}\nArray 2 : {arr2}")
print(f"Indices where elements of two arrays match : {ind}")

Array 1 : [12  7  0 13  9  3 10  8 13  3]
Array 2 : [ 3 13  7 13  6  3  6  6 12  7]
Indices where elements of two arrays match : (array([3, 5]),)

# 13.)
Get all items between 5 and 10 from an array.

In [1]:
import numpy as np

arr = np.random.randint(0, 15, 20)
val = arr[(arr > 5) & (arr < 10)]
print(f"All items between 5 and 10 are {val}")

All items between 5 and 10 are [9 7 6 7 7 9 8 6 9]

# 14.) 
For a 1D array with numeric values, find minimum, maximum, mean, median, standard deviation, 5th and 95th percentile, unique values, count of unique values, and the most frequent value.

In [ ]:
import numpy as np
n = int(input("Enter the number of elements in array : "))
arr = np.zeros((n), dtype='int')
for i in range(n):
    arr[i] = int(input("Enter a value : "))

print(f"Minimum value : {np.amin(arr)}")
print(f"Maximum value : {np.amax(arr)}")
print(f"Mean value : {np.mean(arr)}")
print(f"Median value : {np.median(arr)}")
print(f"Standard Deviation value : {np.std(arr)}")
print(f"5th Percentile value : {np.percentile(arr, 5)}")
print(f"95th Percentile value : {np.percentile(arr, 95)}")
u = np.unique(arr)
print(f"Unique values : {u}")
print(f"Unique values count : {u.size}")
mx_count = 0
mx_count_value = 0
for i in u:
    i_count = np.count_nonzero(arr == i)
    if mx_count < i_count:
        mx_count = i_count
        mx_count_value = i
print(f"Most Frequent value : {mx_count_value}")

Enter the number of elements in array : 2
Enter a value : 1
Enter a value : 5
[1 5]

# 15.)
Write a NumPy program to create a 10x10 matrix, in which all the elements on the borders should be equal to 1, and rest others should be 0.

In [ ]:
import numpy as np
mat = np.zeros((10, 10), dtype='int')
mat[0, :] = 1
mat[:, 0] = 1
mat[9, :] = 1
mat[:, 9] = 1
print(f"The required 10x10 matrix ::\n{mat}")

The required 10x10 matrix ::
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]

# 16.) 
Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5

In [ ]:
import numpy as np
diag_mat = np.diag([1, 2, 3, 4, 5])
print(f"5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5 ::\n{diag_mat}")

5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5 ::
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]

# 17.) 
Count the number of elements in a numpy array which are greater than 10. Further, multiply all such elements with value 10.

In [ ]:
import numpy as np
import numpy as np
a = np.random.randint(20, size=10)
print(f"Array ::\n{a}")

print(f"The number of elements which are greater than 10 : {a[np.nonzero(a>10)].size}")

a[np.nonzero(a>10)] *= 10

print(f"Array after multiplying all the elements with value 10 which are greater than 10 ::\n{a}")

Array ::
[13 12  9  4 13  4 12  9  7 17]
The number of elements which are greater than 10 : 5
Array after multiplying all the elements with value 10 which are greater than 10 ::
[130 120   9   4 130   4 120   9   7 170]